services:
  fast-api:
    build: /api
    image: movies-fastapi
    container_name: movies-api
    ports:
      - "4242:4242"
    volumes:
      - ./api:/code
    environment:
      - API_KEY=eoifastapi
  redis:
    image: "redis:latest"
    container_name: movies-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
